### ISSUE TITLE
getting iframe.contentWindow.location

### ISSUE THREAD

**Issue by funkflute** [mikaturunen/ng-onload#2]
How would you access this.contentWindow.location with this directive from a called function or inside ng-onload=""?

**Comment by mikaturunen** [comment]
This is actually resolved through named parameters now to the callback.

If you take a look at the https://github.com/mikaturunen/ng-onload#usage you can see how it's used. Basically the callback in your controller now receives the iframe.contentWindow.location as parameter so you can use it as you wish. But the location only. 

If you need to do more work with the actual html element instead of just tinkering the location, I would suggest some other solution :) Angular itself does not allow passing the element as a parameter, otherwise we could easily pass the whole element as a parameter into the callback and receive it in the scope but there is a specific check in angular that stops this.

 Hope this helps. I'm considering this issue closed with this and if you have any other bonderings, do drop a line. Happy to help if I can. Thanks!
