### ISSUE TITLE
Const declaration not supported on Safari

### ISSUE THREAD

**Issue by reszli** [mikaturunen/ng-onload#5]
I'm experiencing the following error on iOS/Safari:
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
on line 21: const elementOnloadDirective = () => {

All other browsers work fine.
Any suggestions?

**Comment by mikaturunen** [comment]
It seems you are using the non-compiled version, you need to link against the `/release/ng-onload.min.js`. 

Why does it work in other browsers? Because ES6 by default is supported with those browsers but not with iOS/Safari just yet. `ng-onload` is compiled from ES6 sources to fully ES5 compatible with gulp and the release folder contains the version you should use with your product.

**Comment by reszli** [comment]
me being stupid :) thanks for taking the the time to answer!

**Comment by mikaturunen** [comment]
No worries, I'm super happy to help. Glad I was able to :) Have a nice weekend. 👍
